// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Covenant.API.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for LauncherType.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum LauncherType
    {
        [EnumMember(Value = "Binary")]
        Binary,
        [EnumMember(Value = "ServiceBinary")]
        ServiceBinary,
        [EnumMember(Value = "ShellCode")]
        ShellCode,
        [EnumMember(Value = "PowerShell")]
        PowerShell,
        [EnumMember(Value = "MSBuild")]
        MSBuild,
        [EnumMember(Value = "InstallUtil")]
        InstallUtil,
        [EnumMember(Value = "Regsvr32")]
        Regsvr32,
        [EnumMember(Value = "Mshta")]
        Mshta
    }
    internal static class LauncherTypeEnumExtension
    {
        internal static string ToSerializedValue(this LauncherType? value)
        {
            return value == null ? null : ((LauncherType)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this LauncherType value)
        {
            switch( value )
            {
                case LauncherType.Binary:
                    return "Binary";
                case LauncherType.ServiceBinary:
                    return "ServiceBinary";
                case LauncherType.ShellCode:
                    return "ShellCode";
                case LauncherType.PowerShell:
                    return "PowerShell";
                case LauncherType.MSBuild:
                    return "MSBuild";
                case LauncherType.InstallUtil:
                    return "InstallUtil";
                case LauncherType.Regsvr32:
                    return "Regsvr32";
                case LauncherType.Mshta:
                    return "Mshta";
            }
            return null;
        }

        internal static LauncherType? ParseLauncherType(this string value)
        {
            switch( value )
            {
                case "Binary":
                    return LauncherType.Binary;
                case "ServiceBinary":
                    return LauncherType.ServiceBinary;
                case "ShellCode":
                    return LauncherType.ShellCode;
                case "PowerShell":
                    return LauncherType.PowerShell;
                case "MSBuild":
                    return LauncherType.MSBuild;
                case "InstallUtil":
                    return LauncherType.InstallUtil;
                case "Regsvr32":
                    return LauncherType.Regsvr32;
                case "Mshta":
                    return LauncherType.Mshta;
            }
            return null;
        }
    }
}
