// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Covenant.API.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for CommunicationType.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum CommunicationType
    {
        [EnumMember(Value = "http")]
        Http,
        [EnumMember(Value = "smb")]
        Smb,
        [EnumMember(Value = "bridge")]
        Bridge
    }
    internal static class CommunicationTypeEnumExtension
    {
        internal static string ToSerializedValue(this CommunicationType? value)
        {
            return value == null ? null : ((CommunicationType)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this CommunicationType value)
        {
            switch( value )
            {
                case CommunicationType.Http:
                    return "http";
                case CommunicationType.Smb:
                    return "smb";
                case CommunicationType.Bridge:
                    return "bridge";
            }
            return null;
        }

        internal static CommunicationType? ParseCommunicationType(this string value)
        {
            switch( value )
            {
                case "http":
                    return CommunicationType.Http;
                case "smb":
                    return CommunicationType.Smb;
                case "bridge":
                    return CommunicationType.Bridge;
            }
            return null;
        }
    }
}
