// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Covenant.API.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CommandOutput
    {
        /// <summary>
        /// Initializes a new instance of the CommandOutput class.
        /// </summary>
        public CommandOutput()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CommandOutput class.
        /// </summary>
        public CommandOutput(int gruntCommandId, int? id = default(int?), string output = default(string))
        {
            Id = id;
            Output = output;
            GruntCommandId = gruntCommandId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "output")]
        public string Output { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "gruntCommandId")]
        public int GruntCommandId { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
