// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Covenant.API.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CovenantUserLogin
    {
        /// <summary>
        /// Initializes a new instance of the CovenantUserLogin class.
        /// </summary>
        public CovenantUserLogin()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CovenantUserLogin class.
        /// </summary>
        public CovenantUserLogin(string userName = default(string), string password = default(string))
        {
            UserName = userName;
            Password = password;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userName")]
        public string UserName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "password")]
        public string Password { get; set; }

    }
}
