// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Covenant.API.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for CredentialType.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum CredentialType
    {
        [EnumMember(Value = "password")]
        Password,
        [EnumMember(Value = "hash")]
        Hash,
        [EnumMember(Value = "ticket")]
        Ticket
    }
    internal static class CredentialTypeEnumExtension
    {
        internal static string ToSerializedValue(this CredentialType? value)
        {
            return value == null ? null : ((CredentialType)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this CredentialType value)
        {
            switch( value )
            {
                case CredentialType.Password:
                    return "password";
                case CredentialType.Hash:
                    return "hash";
                case CredentialType.Ticket:
                    return "ticket";
            }
            return null;
        }

        internal static CredentialType? ParseCredentialType(this string value)
        {
            switch( value )
            {
                case "password":
                    return CredentialType.Password;
                case "hash":
                    return CredentialType.Hash;
                case "ticket":
                    return CredentialType.Ticket;
            }
            return null;
        }
    }
}
