// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Covenant.API.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for DownloadProgress.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum DownloadProgress
    {
        [EnumMember(Value = "Portion")]
        Portion,
        [EnumMember(Value = "Complete")]
        Complete
    }
    internal static class DownloadProgressEnumExtension
    {
        internal static string ToSerializedValue(this DownloadProgress? value)
        {
            return value == null ? null : ((DownloadProgress)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this DownloadProgress value)
        {
            switch( value )
            {
                case DownloadProgress.Portion:
                    return "Portion";
                case DownloadProgress.Complete:
                    return "Complete";
            }
            return null;
        }

        internal static DownloadProgress? ParseDownloadProgress(this string value)
        {
            switch( value )
            {
                case "Portion":
                    return DownloadProgress.Portion;
                case "Complete":
                    return DownloadProgress.Complete;
            }
            return null;
        }
    }
}
