// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Covenant.API.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class EmbeddedResource
    {
        /// <summary>
        /// Initializes a new instance of the EmbeddedResource class.
        /// </summary>
        public EmbeddedResource()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the EmbeddedResource class.
        /// </summary>
        public EmbeddedResource(int? id = default(int?), string name = default(string), string location = default(string))
        {
            Id = id;
            Name = name;
            Location = location;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "location")]
        public string Location { get; set; }

    }
}
