// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Covenant.API.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for EventLevel.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum EventLevel
    {
        [EnumMember(Value = "Silent")]
        Silent,
        [EnumMember(Value = "Info")]
        Info,
        [EnumMember(Value = "Warning")]
        Warning,
        [EnumMember(Value = "Highlight")]
        Highlight,
        [EnumMember(Value = "Error")]
        Error
    }
    internal static class EventLevelEnumExtension
    {
        internal static string ToSerializedValue(this EventLevel? value)
        {
            return value == null ? null : ((EventLevel)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this EventLevel value)
        {
            switch( value )
            {
                case EventLevel.Silent:
                    return "Silent";
                case EventLevel.Info:
                    return "Info";
                case EventLevel.Warning:
                    return "Warning";
                case EventLevel.Highlight:
                    return "Highlight";
                case EventLevel.Error:
                    return "Error";
            }
            return null;
        }

        internal static EventLevel? ParseEventLevel(this string value)
        {
            switch( value )
            {
                case "Silent":
                    return EventLevel.Silent;
                case "Info":
                    return EventLevel.Info;
                case "Warning":
                    return EventLevel.Warning;
                case "Highlight":
                    return EventLevel.Highlight;
                case "Error":
                    return EventLevel.Error;
            }
            return null;
        }
    }
}
