// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Covenant.API.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class FileIndicator
    {
        /// <summary>
        /// Initializes a new instance of the FileIndicator class.
        /// </summary>
        public FileIndicator()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the FileIndicator class.
        /// </summary>
        /// <param name="type">Possible values include: 'FileIndicator',
        /// 'NetworkIndicator', 'TargetIndicator'</param>
        public FileIndicator(string fileName = default(string), string filePath = default(string), string shA2 = default(string), string shA1 = default(string), string mD5 = default(string), int? id = default(int?), IndicatorType? type = default(IndicatorType?))
        {
            FileName = fileName;
            FilePath = filePath;
            ShA2 = shA2;
            ShA1 = shA1;
            MD5 = mD5;
            Id = id;
            Type = type;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fileName")]
        public string FileName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "filePath")]
        public string FilePath { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "shA2")]
        public string ShA2 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "shA1")]
        public string ShA1 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mD5")]
        public string MD5 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'FileIndicator',
        /// 'NetworkIndicator', 'TargetIndicator'
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public IndicatorType? Type { get; set; }

    }
}
