// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Covenant.API.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for GruntTaskingType.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum GruntTaskingType
    {
        [EnumMember(Value = "assembly")]
        Assembly,
        [EnumMember(Value = "setOption")]
        SetOption,
        [EnumMember(Value = "exit")]
        Exit,
        [EnumMember(Value = "connect")]
        Connect,
        [EnumMember(Value = "disconnect")]
        Disconnect,
        [EnumMember(Value = "jobs")]
        Jobs
    }
    internal static class GruntTaskingTypeEnumExtension
    {
        internal static string ToSerializedValue(this GruntTaskingType? value)
        {
            return value == null ? null : ((GruntTaskingType)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this GruntTaskingType value)
        {
            switch( value )
            {
                case GruntTaskingType.Assembly:
                    return "assembly";
                case GruntTaskingType.SetOption:
                    return "setOption";
                case GruntTaskingType.Exit:
                    return "exit";
                case GruntTaskingType.Connect:
                    return "connect";
                case GruntTaskingType.Disconnect:
                    return "disconnect";
                case GruntTaskingType.Jobs:
                    return "jobs";
            }
            return null;
        }

        internal static GruntTaskingType? ParseGruntTaskingType(this string value)
        {
            switch( value )
            {
                case "assembly":
                    return GruntTaskingType.Assembly;
                case "setOption":
                    return GruntTaskingType.SetOption;
                case "exit":
                    return GruntTaskingType.Exit;
                case "connect":
                    return GruntTaskingType.Connect;
                case "disconnect":
                    return GruntTaskingType.Disconnect;
                case "jobs":
                    return GruntTaskingType.Jobs;
            }
            return null;
        }
    }
}
