// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Covenant.API.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class GruntTaskOption
    {
        /// <summary>
        /// Initializes a new instance of the GruntTaskOption class.
        /// </summary>
        public GruntTaskOption()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GruntTaskOption class.
        /// </summary>
        public GruntTaskOption(int? id = default(int?), int? taskId = default(int?), int? optionId = default(int?), string name = default(string), string description = default(string), string value = default(string))
        {
            Id = id;
            TaskId = taskId;
            OptionId = optionId;
            Name = name;
            Description = description;
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "taskId")]
        public int? TaskId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "optionId")]
        public int? OptionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

    }
}
