// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Covenant.API.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for GruntStatus.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum GruntStatus
    {
        [EnumMember(Value = "uninitialized")]
        Uninitialized,
        [EnumMember(Value = "stage0")]
        Stage0,
        [EnumMember(Value = "stage1")]
        Stage1,
        [EnumMember(Value = "stage2")]
        Stage2,
        [EnumMember(Value = "active")]
        Active,
        [EnumMember(Value = "lost")]
        Lost,
        [EnumMember(Value = "exited")]
        Exited,
        [EnumMember(Value = "disconnected")]
        Disconnected,
        [EnumMember(Value = "hidden")]
        Hidden
    }
    internal static class GruntStatusEnumExtension
    {
        internal static string ToSerializedValue(this GruntStatus? value)
        {
            return value == null ? null : ((GruntStatus)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this GruntStatus value)
        {
            switch( value )
            {
                case GruntStatus.Uninitialized:
                    return "uninitialized";
                case GruntStatus.Stage0:
                    return "stage0";
                case GruntStatus.Stage1:
                    return "stage1";
                case GruntStatus.Stage2:
                    return "stage2";
                case GruntStatus.Active:
                    return "active";
                case GruntStatus.Lost:
                    return "lost";
                case GruntStatus.Exited:
                    return "exited";
                case GruntStatus.Disconnected:
                    return "disconnected";
                case GruntStatus.Hidden:
                    return "hidden";
            }
            return null;
        }

        internal static GruntStatus? ParseGruntStatus(this string value)
        {
            switch( value )
            {
                case "uninitialized":
                    return GruntStatus.Uninitialized;
                case "stage0":
                    return GruntStatus.Stage0;
                case "stage1":
                    return GruntStatus.Stage1;
                case "stage2":
                    return GruntStatus.Stage2;
                case "active":
                    return GruntStatus.Active;
                case "lost":
                    return GruntStatus.Lost;
                case "exited":
                    return GruntStatus.Exited;
                case "disconnected":
                    return GruntStatus.Disconnected;
                case "hidden":
                    return GruntStatus.Hidden;
            }
            return null;
        }
    }
}
