// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Covenant.API.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class GruntTaskingMessage
    {
        /// <summary>
        /// Initializes a new instance of the GruntTaskingMessage class.
        /// </summary>
        public GruntTaskingMessage()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GruntTaskingMessage class.
        /// </summary>
        /// <param name="type">Possible values include: 'Assembly', 'SetDelay',
        /// 'SetJitter', 'SetConnectAttempts', 'Exit', 'Connect', 'Disconnect',
        /// 'Jobs'</param>
        public GruntTaskingMessage(GruntTaskingType? type = default(GruntTaskingType?), string name = default(string), string message = default(string), bool? token = default(bool?))
        {
            Type = type;
            Name = name;
            Message = message;
            Token = token;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets possible values include: 'Assembly', 'SetDelay',
        /// 'SetJitter', 'SetConnectAttempts', 'Exit', 'Connect', 'Disconnect',
        /// 'Jobs'
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public GruntTaskingType? Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "token")]
        public bool? Token { get; set; }

    }
}
