// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Covenant.API.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for GruntTaskingStatus.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum GruntTaskingStatus
    {
        [EnumMember(Value = "uninitialized")]
        Uninitialized,
        [EnumMember(Value = "tasked")]
        Tasked,
        [EnumMember(Value = "progressed")]
        Progressed,
        [EnumMember(Value = "completed")]
        Completed,
        [EnumMember(Value = "aborted")]
        Aborted
    }
    internal static class GruntTaskingStatusEnumExtension
    {
        internal static string ToSerializedValue(this GruntTaskingStatus? value)
        {
            return value == null ? null : ((GruntTaskingStatus)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this GruntTaskingStatus value)
        {
            switch( value )
            {
                case GruntTaskingStatus.Uninitialized:
                    return "uninitialized";
                case GruntTaskingStatus.Tasked:
                    return "tasked";
                case GruntTaskingStatus.Progressed:
                    return "progressed";
                case GruntTaskingStatus.Completed:
                    return "completed";
                case GruntTaskingStatus.Aborted:
                    return "aborted";
            }
            return null;
        }

        internal static GruntTaskingStatus? ParseGruntTaskingStatus(this string value)
        {
            switch( value )
            {
                case "uninitialized":
                    return GruntTaskingStatus.Uninitialized;
                case "tasked":
                    return GruntTaskingStatus.Tasked;
                case "progressed":
                    return GruntTaskingStatus.Progressed;
                case "completed":
                    return GruntTaskingStatus.Completed;
                case "aborted":
                    return GruntTaskingStatus.Aborted;
            }
            return null;
        }
    }
}
