// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Covenant.API.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class GruntTasking
    {
        /// <summary>
        /// Initializes a new instance of the GruntTasking class.
        /// </summary>
        public GruntTasking()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GruntTasking class.
        /// </summary>
        /// <param name="status">Possible values include: 'Uninitialized',
        /// 'Tasked', 'Progressed', 'Completed'</param>
        /// <param name="type">Possible values include: 'Assembly', 'Set',
        /// 'Kill'</param>
        /// <param name="setType">Possible values include: 'Delay', 'Jitter',
        /// 'ConnectAttempts'</param>
        public GruntTasking(int? id = default(int?), string name = default(string), int? taskId = default(int?), int? gruntId = default(int?), GruntTaskingStatus? status = default(GruntTaskingStatus?), GruntTaskingType? type = default(GruntTaskingType?), string gruntTaskOutput = default(string), GruntTaskingMessage taskingMessage = default(GruntTaskingMessage), string gruntTaskingAssembly = default(string), GruntSetTaskingType? setType = default(GruntSetTaskingType?), string value = default(string))
        {
            Id = id;
            Name = name;
            TaskId = taskId;
            GruntId = gruntId;
            Status = status;
            Type = type;
            GruntTaskOutput = gruntTaskOutput;
            TaskingMessage = taskingMessage;
            GruntTaskingAssembly = gruntTaskingAssembly;
            SetType = setType;
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "taskId")]
        public int? TaskId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "gruntId")]
        public int? GruntId { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Uninitialized', 'Tasked',
        /// 'Progressed', 'Completed'
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public GruntTaskingStatus? Status { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Assembly', 'Set', 'Kill'
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public GruntTaskingType? Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "gruntTaskOutput")]
        public string GruntTaskOutput { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "taskingMessage")]
        public GruntTaskingMessage TaskingMessage { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "gruntTaskingAssembly")]
        public string GruntTaskingAssembly { get; private set; }

        /// <summary>
        /// Gets or sets possible values include: 'Delay', 'Jitter',
        /// 'ConnectAttempts'
        /// </summary>
        [JsonProperty(PropertyName = "setType")]
        public GruntSetTaskingType? SetType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

    }
}
