// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Covenant.API.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for GruntTaskingType.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum GruntTaskingType
    {
        [EnumMember(Value = "Assembly")]
        Assembly,
        [EnumMember(Value = "SetDelay")]
        SetDelay,
        [EnumMember(Value = "SetJitter")]
        SetJitter,
        [EnumMember(Value = "SetConnectAttempts")]
        SetConnectAttempts,
        [EnumMember(Value = "SetKillDate")]
        SetKillDate,
        [EnumMember(Value = "Exit")]
        Exit,
        [EnumMember(Value = "Connect")]
        Connect,
        [EnumMember(Value = "Disconnect")]
        Disconnect,
        [EnumMember(Value = "Tasks")]
        Tasks,
        [EnumMember(Value = "TaskKill")]
        TaskKill
    }
    internal static class GruntTaskingTypeEnumExtension
    {
        internal static string ToSerializedValue(this GruntTaskingType? value)
        {
            return value == null ? null : ((GruntTaskingType)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this GruntTaskingType value)
        {
            switch( value )
            {
                case GruntTaskingType.Assembly:
                    return "Assembly";
                case GruntTaskingType.SetDelay:
                    return "SetDelay";
                case GruntTaskingType.SetJitter:
                    return "SetJitter";
                case GruntTaskingType.SetConnectAttempts:
                    return "SetConnectAttempts";
                case GruntTaskingType.SetKillDate:
                    return "SetKillDate";
                case GruntTaskingType.Exit:
                    return "Exit";
                case GruntTaskingType.Connect:
                    return "Connect";
                case GruntTaskingType.Disconnect:
                    return "Disconnect";
                case GruntTaskingType.Tasks:
                    return "Tasks";
                case GruntTaskingType.TaskKill:
                    return "TaskKill";
            }
            return null;
        }

        internal static GruntTaskingType? ParseGruntTaskingType(this string value)
        {
            switch( value )
            {
                case "Assembly":
                    return GruntTaskingType.Assembly;
                case "SetDelay":
                    return GruntTaskingType.SetDelay;
                case "SetJitter":
                    return GruntTaskingType.SetJitter;
                case "SetConnectAttempts":
                    return GruntTaskingType.SetConnectAttempts;
                case "SetKillDate":
                    return GruntTaskingType.SetKillDate;
                case "Exit":
                    return GruntTaskingType.Exit;
                case "Connect":
                    return GruntTaskingType.Connect;
                case "Disconnect":
                    return GruntTaskingType.Disconnect;
                case "Tasks":
                    return GruntTaskingType.Tasks;
                case "TaskKill":
                    return GruntTaskingType.TaskKill;
            }
            return null;
        }
    }
}
