// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Covenant.API.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for HashType.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum HashType
    {
        [EnumMember(Value = "NTLM")]
        NTLM,
        [EnumMember(Value = "LM")]
        LM,
        [EnumMember(Value = "SHA1")]
        SHA1
    }
    internal static class HashTypeEnumExtension
    {
        internal static string ToSerializedValue(this HashType? value)
        {
            return value == null ? null : ((HashType)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this HashType value)
        {
            switch( value )
            {
                case HashType.NTLM:
                    return "NTLM";
                case HashType.LM:
                    return "LM";
                case HashType.SHA1:
                    return "SHA1";
            }
            return null;
        }

        internal static HashType? ParseHashType(this string value)
        {
            switch( value )
            {
                case "NTLM":
                    return HashType.NTLM;
                case "LM":
                    return HashType.LM;
                case "SHA1":
                    return HashType.SHA1;
            }
            return null;
        }
    }
}
