// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Covenant.API.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for ImplantLanguage.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ImplantLanguage
    {
        [EnumMember(Value = "cSharp")]
        CSharp
    }
    internal static class ImplantLanguageEnumExtension
    {
        internal static string ToSerializedValue(this ImplantLanguage? value)
        {
            return value == null ? null : ((ImplantLanguage)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this ImplantLanguage value)
        {
            switch( value )
            {
                case ImplantLanguage.CSharp:
                    return "cSharp";
            }
            return null;
        }

        internal static ImplantLanguage? ParseImplantLanguage(this string value)
        {
            switch( value )
            {
                case "cSharp":
                    return ImplantLanguage.CSharp;
            }
            return null;
        }
    }
}
