// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Covenant.API.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for ImplantDirection.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ImplantDirection
    {
        [EnumMember(Value = "Push")]
        Push,
        [EnumMember(Value = "Pull")]
        Pull
    }
    internal static class ImplantDirectionEnumExtension
    {
        internal static string ToSerializedValue(this ImplantDirection? value)
        {
            return value == null ? null : ((ImplantDirection)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this ImplantDirection value)
        {
            switch( value )
            {
                case ImplantDirection.Push:
                    return "Push";
                case ImplantDirection.Pull:
                    return "Pull";
            }
            return null;
        }

        internal static ImplantDirection? ParseImplantDirection(this string value)
        {
            switch( value )
            {
                case "Push":
                    return ImplantDirection.Push;
                case "Pull":
                    return ImplantDirection.Pull;
            }
            return null;
        }
    }
}
