// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Covenant.API.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for IntegrityLevel.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum IntegrityLevel
    {
        [EnumMember(Value = "untrusted")]
        Untrusted,
        [EnumMember(Value = "low")]
        Low,
        [EnumMember(Value = "medium")]
        Medium,
        [EnumMember(Value = "high")]
        High,
        [EnumMember(Value = "system")]
        System
    }
    internal static class IntegrityLevelEnumExtension
    {
        internal static string ToSerializedValue(this IntegrityLevel? value)
        {
            return value == null ? null : ((IntegrityLevel)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this IntegrityLevel value)
        {
            switch( value )
            {
                case IntegrityLevel.Untrusted:
                    return "untrusted";
                case IntegrityLevel.Low:
                    return "low";
                case IntegrityLevel.Medium:
                    return "medium";
                case IntegrityLevel.High:
                    return "high";
                case IntegrityLevel.System:
                    return "system";
            }
            return null;
        }

        internal static IntegrityLevel? ParseIntegrityLevel(this string value)
        {
            switch( value )
            {
                case "untrusted":
                    return IntegrityLevel.Untrusted;
                case "low":
                    return IntegrityLevel.Low;
                case "medium":
                    return IntegrityLevel.Medium;
                case "high":
                    return IntegrityLevel.High;
                case "system":
                    return IntegrityLevel.System;
            }
            return null;
        }
    }
}
