// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Covenant.API.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ReferenceAssembly
    {
        /// <summary>
        /// Initializes a new instance of the ReferenceAssembly class.
        /// </summary>
        public ReferenceAssembly()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ReferenceAssembly class.
        /// </summary>
        /// <param name="dotNetVersion">Possible values include: 'Net35',
        /// 'Net40', 'NetCore31'</param>
        public ReferenceAssembly(int? id = default(int?), string name = default(string), string location = default(string), DotNetVersion? dotNetVersion = default(DotNetVersion?))
        {
            Id = id;
            Name = name;
            Location = location;
            DotNetVersion = dotNetVersion;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "location")]
        public string Location { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Net35', 'Net40', 'NetCore31'
        /// </summary>
        [JsonProperty(PropertyName = "dotNetVersion")]
        public DotNetVersion? DotNetVersion { get; set; }

    }
}
