// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Covenant.API.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for ScriptingLanguage.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ScriptingLanguage
    {
        [EnumMember(Value = "jScript")]
        JScript,
        [EnumMember(Value = "vbScript")]
        VbScript
    }
    internal static class ScriptingLanguageEnumExtension
    {
        internal static string ToSerializedValue(this ScriptingLanguage? value)
        {
            return value == null ? null : ((ScriptingLanguage)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this ScriptingLanguage value)
        {
            switch( value )
            {
                case ScriptingLanguage.JScript:
                    return "jScript";
                case ScriptingLanguage.VbScript:
                    return "vbScript";
            }
            return null;
        }

        internal static ScriptingLanguage? ParseScriptingLanguage(this string value)
        {
            switch( value )
            {
                case "jScript":
                    return ScriptingLanguage.JScript;
                case "vbScript":
                    return ScriptingLanguage.VbScript;
            }
            return null;
        }
    }
}
